### ISSUE TITLE
getCollection only fetches root collections

### ISSUE THREAD

**Issue by ropaolle** [steadyequipment/node-firestore-backup#12]
Nice module. Great job.

FYI. Did a quick test and noticed that getCollections only fetches root collections, i.e. collections that is children to a document is ignored.

**Comment by ropaolle** [comment]
Did some more testing and this only applies to collections under a "hidden" document. Still a noob so I am not sure I understand this but I think collections connected to a empty document is hidden. In the Firestore admin they are marked as disabled (budget/_items_/expenses).

Collections that are children to a document without any other fields are ignored. 

But to be honest that seems like an edge case. If the document don't have any other fields the collection 
can as well be moved to the root. Anyway, maybe good to know.

![screen shot 12-19-17 at 01 50 pm](https://user-images.githubusercontent.com/4247624/34159423-8a5a4d72-e4c9-11e7-9dfa-fa96beac9190.PNG)

**Comment by yoiang** [comment]
Hmmm, good find!
