### ISSUE TITLE
Add ability to include or exclude paths

### ISSUE THREAD

**Issue by yoiang** [steadyequipment/node-firestore-backup#27]
If include is used then only collections and documents that match include and do not match exclude are backed up

**Comment by lewchuk** [comment]
I'm thinking that supporting an `excludePattern` parameter might be a good way to solve this problem. The would let you be pretty exact in the exclusion. Given a setup like:

```
/organizations - collection
  /org-1 - document
    /messages - sub collection
    /backup
  /org-2
    /messages
    /backup
/other
```

- Exclude top level collection: `^/other`
- Exclude sub collections of all documents: `^/organizations/[^/]*/backup`
- Exclude a particular document: `^/organizations/org-2`

Thoughts?

**Comment by yoiang** [comment]
Closing thanks to @lewchuk 's contribution in #31 and in favor of the more concise issue #37

**Comment by lewchuk** [comment]
@yoiang What is the schedule for getting a new npm package version published? Is there anything I can do to help that process?

**Comment by yoiang** [comment]
I was hoping to release when some dependency issues were resolved (#34), but it isn't clear when that is getting resolved. 

Let me push up a new release!

**Comment by yoiang** [comment]
Done!
https://www.npmjs.com/package/firestore-backup/v/2.3.0
https://github.com/steadyequipment/node-firestore-backup/releases/tag/2.3.0

**Comment by lewchuk** [comment]
Thanks @yoiang!
