### ISSUE TITLE
databaseStartPath does not work

### ISSUE THREAD

**Issue by martinkronstad** [steadyequipment/node-firestore-backup#29]
databaseStartPath does not seem to do anything. 

Doing this will back up everything:

sudo firestore-backup -a sAccount.json --databaseStartPath /orgs -B ./april/06/

**Comment by lewchuk-inkling** [comment]
I believe the order of the arguments to this `Object.assign` needs to be reversed: https://github.com/steadyequipment/node-firestore-backup/blob/master/lib/index.js#L20. The empty string value of `databaseStartPath` is overwritting any passed in the options.
