### ISSUE TITLE
Collection backup not working

### ISSUE THREAD

**Issue by andreescocard** [steadyequipment/node-firestore-backup#45]
Tried backuping up, says "All Done" with folders with the collections names but nothing inside the folders.
What am i doing wrong?
Thanks

**Comment by gloss-water** [comment]
@andreescocard post the command you're using

**Comment by andreescocard** [comment]
Tried all commands, none of them work
I don't need this anymore, migrated all data to realtime
And i think all backup tools including this one should not work anymore
To backup/import firestore needs to use gcloud with blaze plan: https://firebase.google.com/docs/firestore/manage-data/export-import

**Comment by gloss-water** [comment]
why should it not work? it just uses the firebase admin sdk to read from the db.  it's a viable option, though the gcloud import/export is the "better" one

tested today on a large database and it worked correctly

**Comment by andreescocard** [comment]
I think that the problem is happening because of the way i design the database.
In my case:
-agendas
--id1
---mine
----doc1
----doc2
----doc3
--id2
---mine
----doc1
----doc2
----doc3
--id3
---mine
----doc1
----doc2
----doc3

**Comment by yoiang** [comment]
I've just tested the library against the test database and it still functions a-ok.  I'm going to close the issue until there is insight into why it may not have been working.
