### ISSUE TITLE
Upload account credentials example

### ISSUE THREAD

**Issue by rootux** [steadyequipment/node-firestore-backup#5]
Hey. Would be nice if you add some kind of 'assets' folder with account credentials example and add it in the README.

**Comment by yoiang** [comment]
Ah perfect idea! When I have a sec I'll add that, feel free to create a Pull Request!

**Comment by yoiang** [comment]
Would also be great to include or link to instructions on getting the credentials from the Firebase dashboard.

**Comment by ArpitKotecha** [comment]
Created pull request about that

**Comment by yoiang** [comment]
Merge, thanks again @ArpitKotecha !
