### ISSUE TITLE
Provide an API

### ISSUE THREAD

**Issue by saintplay** [steadyequipment/node-firestore-backup#9]
It would be nice to be able to do this programmatically

**Comment by yoiang** [comment]
Was this what you were thinking? 
Pull Request #10

**Comment by saintplay** [comment]
Yeah! looks very promising,

Maybe passing the serviceAccount as a json instead of the path is better idea.
Similar to how firebase-admin works

```js
import backup from "node-firestore-backup";

const serviceAccount = require("path/to/serviceAccountKey.json");

backup(serviceAccount, '/backups/new', true)
```

**Comment by kylehotchkiss** [comment]
hey there! If this was merged it would help my team and I - we want to run a firebase functions script that can run our backups for us

**Comment by yoiang** [comment]
Sorry about that, updated with your suggestions @saintplay, and merged!

**Comment by kylehotchkiss** [comment]
@yoiang perfect timing :D i will put this to work right away
